---
- name: install system-packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    force_apt_get: yes
  loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: install docker GPG apt key
  apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: install docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: install docker
  apt:
   update_cache: yes
   name: docker-ce
   state: latest

- name: add remote user to group docker
  command: usermod -aG docker ubuntu

- name: Enable and check Docker service
  service:
    name: docker
    state: restarted
    enabled: yes
  register: started_docker

- name: enable if command above does strange things (debug me)
  command: systemctl enable docker