---
- name: install system-packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: ['wget','git','apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: install docker GPG apt key
  apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: install docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install docker and containerd 
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: [ 'docker-ce', 'containerd.io', 'docker-ce-cli']

- name: Create docker systemd directory
  command: "sudo mkdir -p /etc/systemd/system/docker.service.d"

- name: Copy docker config json
  template: 
    src: "../templates/daemon.json.j2"
    dest: "/etc/docker/daemon.json"
  register: docker_daemon_copied
   
- name: daemon reload - docker
  command: systemctl daemon-reload

- name: service restart docker
  command: systemctl restart docker

- name: service enable docker
  command: systemctl enable docker

- name: add remote user to group docker
  command: usermod -aG docker ubuntu

- name: Download latest cri-dockerd binary
  command: "wget https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.1/cri-dockerd-0.3.1.amd64.tgz"
  register: cri_dockerd_download

- name: untar cri-dockerd binary
  when: cri_dockerd_download| success
  command: "tar xvf cri-dockerd-0.3.1.amd64.tgz"
  register: cri_dockerd_binary_untar

- name: move cri-dockerd to bin
  when: cri_dockerd_binary_untar| success
  command: "mv cri-dockerd/cri-dockerd /usr/local/bin/"
  register: moved_cri_dockerd

- name: Copy cri-docker.service to systemd 
  template: 
    src: "../templates/cri-docker.service.j2"
    dest: "/etc/systemd/system/cri-docker.service"
  register: cri-docker.service_copied

- name: Copy cri-docker.socket to systemd 
  template: 
    src: "../templates/cri-docker.socket.j2"
    dest: "/etc/systemd/system/cri-docker.socket"
  register: cri-docker.service_copied

- name: add remote user to group docker
  command: usermod -aG docker ubuntu

- name: daemon reload - cri-docker
  command: systemctl daemon-reload

- name: service enable cri-docker.service
  command: systemctl enable cri-docker.service

- name: service enable cri-docker.socket
  command: systemctl enable --now cri-docker.socket 


# - name: Enable and check Docker service
#   service:
#     name: docker
#     state: restarted
#     enabled: yes
#   register: started_docker

# - name: enable if command above does strange things (debug me)
#   command: systemctl enable docker